In [11]:
import numpy as np

In [12]:
n1=np.arange(12)
print(n1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [14]:
print("data type of n1:",type(n1))

data type of n1: <class 'numpy.ndarray'>


In [15]:
print("dimension of n1:",n1.ndim)

dimension of n1: 1


In [16]:
print("shape of n1:",n1.shape)

shape of n1: (12,)


In [17]:
print("data type of each element:",n1.dtype)

data type of each element: int32


In [18]:
n1.reshape(3,4)
print(n1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [19]:
n2=n1.reshape(3,4)
print(n2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
print("data type of n2:",type(n2))

data type of n2: <class 'numpy.ndarray'>


In [21]:
print("dimension:",n2.ndim)

dimension: 2


In [22]:
print("shape:",n2.shape)

shape: (3, 4)


In [23]:
print("data type of each element:",n2.dtype)

data type of each element: int32


In [39]:
B=array.array('i',[1,4,9,16])
print(B)

array('i', [1, 4, 9, 16])


In [32]:
import array

In [36]:
a=array.array('i',[1,2,4,9,16,25])
print(a)

array('i', [1, 2, 4, 9, 16, 25])


In [37]:
print("data type of:",type(a))

data type of: <class 'array.array'>
